"""Increase length of columns

Revision ID: 9c728b1712d9
Revises: a8caa3547d57
Create Date: 2024-12-15 20:52:14.396859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c728b1712d9'
down_revision: Union[str, None] = 'a8caa3547d57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('auto_update', sa.Boolean(), default = False))
    op.add_column('users', sa.Column('refresh_token', sa.String(length = 256), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###  