"""Add new columns to Users table

Revision ID: a8caa3547d57
Revises: be436e9513ee
Create Date: 2024-12-15 20:22:36.799787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8caa3547d57'
down_revision: Union[str, None] = 'be436e9513ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'refresh_token')
    op.drop_column('users', 'auto_update')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('auto_update', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('refresh_token', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
