"""Add new columns to Users table

Revision ID: be436e9513ee
Revises: 
Create Date: 2024-12-04 18:55:04.282660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be436e9513ee'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:

    op.add_column('users', sa.Column('auto_update', sa.Boolean))
    op.add_column('users', sa.Column('refresh_token', sa.String(length=64)))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
